version: '3.9'
services:
  backend:
    build: .
    container_name: academic_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:18
    container_name: academic_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: academic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
